title: Rabbits Rabbits 
author: Edwin Riley 
email: edwinthomasr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am here to talk about rabbits! 
  *hop hop hop* 

# social links
twitter_username: e28e7065b740437
github_username:  edwinthomasr

show_excerpts: true 
theme: minima 
